version: '3.7'

services:

  feverchallenge:
    build:
      context: app
      dockerfile: Dockerfile
      target: feverchallenge_app
    volumes:
      - './:/code'
    ports:
      - 8000:8000
    # env_file:
    #   - app/.env
    networks:
      - feverchallenge_net


networks:
  feverchallenge_net:
    internal: false
